# -*- coding: utf-8 -*-
"""Programming Assignment_13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t3SAOMpqIPdVJwOMpurYCUC4FvZ5L_1P

# Python Programming Basic Assignment 13

### 1. Write a program that calculates and prints the value according to the given formula:
Q = Square root of [(2 C D)/H]

Following are the fixed values of C and H:

C is 50. H is 30.

D is the variable whose values should be input to your program in a comma-separated sequence.

Example

Let us assume the following comma separated input sequence is given to the program:

100,150,180

The output of the program should be:

18,22,24
"""

import math

C = 50
H = 30

# Get the input values as a comma-separated string and split into a list
D = input("Enter comma-separated values for D: ").split(",")

result = []
for d in D:
    # Calculate the value of Q for each value of D
    Q = round(math.sqrt((2 * C * int(d))/H))
    result.append(Q)

# Convert the result list to a comma-separated string and print it
print(",".join(str(q) for q in result))

"""### 2. Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional array. The element value in the i-th row and j-th column of the array should be i*j."""

X = int(input("Enter the number of rows: "))
Y = int(input("Enter the number of columns: "))

# Generate the 2-dimensional array
arr = [[i*j for j in range(Y)] for i in range(X)]

# Print the array
for i in range(X):
    for j in range(Y):
        print(arr[i][j], end=" ")
    print()

"""### 3. Write a program that accepts a comma separated sequence of words as input and prints the words in a comma-separated sequence after sorting them alphabetically."""

# Accept input
words = input("Enter comma-separated words: ")

# Split words by comma and sort alphabetically
sorted_words = sorted(words.split(","))

# Join sorted words by comma and print
print(",".join(sorted_words))

"""### 4. Write a program that accepts a sequence of whitespace separated words as input and prints the words after removing all duplicate words and sorting them alphanumerically."""

words = input("Enter whitespace separated words: ").split()
unique_words = sorted(set(words))
result = " ".join(unique_words)
print(result)

"""### 5. Write a program that accepts a sentence and calculate the number of letters and digits."""

sentence = input("Enter a sentence: ")

num_letters = 0
num_digits = 0

for char in sentence:
    if char.isalpha():
        num_letters += 1
    elif char.isdigit():
        num_digits += 1

print("Number of letters:", num_letters)
print("Number of digits:", num_digits)

"""### 6. A website requires the users to input username and password to register. Write a program to check the validity of password input by users."""

import re

password = input("Enter password: ")

# Check if password has at least 8 characters
if len(password) < 8:
    print("Password must be at least 8 characters long")
else:
    # Check if password has at least one uppercase letter
    if not re.search("[A-Z]", password):
        print("Password must contain at least one uppercase letter")
    # Check if password has at least one lowercase letter
    elif not re.search("[a-z]", password):
        print("Password must contain at least one lowercase letter")
    # Check if password has at least one digit
    elif not re.search("[0-9]", password):
        print("Password must contain at least one digit")
    else:
        print("Password is valid")

