# -*- coding: utf-8 -*-
"""Programming Assignment_2 (1).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10h2ixLL9Brcv5hYwJiY_XkNnK3cVvFNG

## Programming Assignment_2
-------------

1. Write a Python program to convert kilometers to miles?
"""

# Get the distance in kilometers from the user
kilometers = float(input("Enter the distance in kilometers: "))

# Convert kilometers to miles
conversion_factor = 0.621371
miles = kilometers * conversion_factor

# Print the distance in miles
print(kilometers, "kilometers is equal to", miles, "miles.")

"""### 2.Write a Python program to convert Celsius to Fahrenheit?"""

# Get the temperature in Celsius from the user
celsius = float(input("Enter the temperature in Celsius: "))

# Convert Celsius to Fahrenheit
fahrenheit = (celsius * 9/5) + 32

# Print the temperature in Fahrenheit
print(celsius, "degrees Celsius is equal to", fahrenheit, "degrees Fahrenheit.")

"""3. Write a Python program to display calendar?

"""

import calendar

# Get the year and month from the user
year = int(input("Enter the year: "))
month = int(input("Enter the month: "))

# Display the calendar for the given year and month
print(calendar.month(year, month))

"""### 4. Write a Python program to solve quadratic equation?"""

# Import the math module
import math

# Get the coefficients of the quadratic equation from the user
a = float(input("Enter the value of a: "))
b = float(input("Enter the value of b: "))
c = float(input("Enter the value of c: "))

# Calculate the discriminant
discriminant = b**2 - 4*a*c

# Check if the discriminant is positive, negative, or zero
if discriminant > 0:
    # Two real solutions
    x1 = (-b + math.sqrt(discriminant)) / (2*a)
    x2 = (-b - math.sqrt(discriminant)) / (2*a)
    print("The solutions are:", x1, "and", x2)
elif discriminant == 0:
    # One real solution
    x = -b / (2*a)
    print("The solution is:", x)
else:
    # Two complex solutions
    real_part = -b / (2*a)
    imaginary_part = math.sqrt(-discriminant) / (2*a)
    print("The solutions are:", real_part, "+", imaginary_part, "i and", real_part, "-", imaginary_part, "i")

"""5. Write a Python program to swap two variables without temp variable?"""

# Get the values of the variables from the user
a = int(input("Enter the value of a: "))
b = int(input("Enter the value of b: "))

# Print the values of the variables before swapping
print("Before swapping, a =", a, "and b =", b)

# Swap the values of the variables
a = a + b
b = a - b
a = a - b

# Print the values of the variables after swapping
print("After swapping, a =", a, "and b =", b)

