# -*- coding: utf-8 -*-
"""Programming Assignment_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16OwahNNnH6iZmsTlrKBWDVzQ6oNNIFIW

## Programming Assignment_3
----------------

### 1. Write a Python Program to Check if a Number is Positive, Negative or Zero?
"""

# Get the number from the user
num = float(input("Enter a number: "))

# Check if the number is positive, negative, or zero
if num > 0:
    print(num, "is a positive number")
elif num == 0:
    print(num, "is zero")
else:
    print(num, "is a negative number")

"""### 2. Write a Python Program to Check if a Number is Odd or Even?

"""

# Get the number from the user
num = int(input("Enter a number: "))

# Check if the number is odd or even
if num % 2 == 0:
    print(num, "is an even number")
else:
    print(num, "is an odd number")

"""\### 3. Write a Python Program to Check Leap Year?

"""

# Get the year from the user
year = int(input("Enter a year: "))

# Check if the year is a leap year or not
if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
    print(year, "is a leap year")
else:
    print(year, "is not a leap year")

"""### 4. Write a Python Program to Check Prime Number?"""

# Get the number from the user
num = int(input("Enter a number: "))

# Check if the number is prime or not
if num > 1:
    for i in range(2, num):
        if (num % i) == 0:
            print(num, "is not a prime number")
            break
    else:
        print(num, "is a prime number")
else:
    print(num, "is not a prime number")

"""### 5. Write a Python Program to Print all Prime Numbers in an Interval of 1-10000?"""

# Define a function to check if a number is prime
def is_prime(num):
    if num > 1:
        for i in range(2, num):
            if (num % i) == 0:
                return False
        else:
            return True
    else:
        return False

# Print all prime numbers in the interval of 1-10000
for i in range(1, 10001):
    if is_prime(i):
        print(i)

