# -*- coding: utf-8 -*-
"""Programming Assignment_5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KfTAepiNPkIPm35X39MBPDMcnnskholU

## Python Basic Programming Assignment - 5
--------------

### 1. Write a Python Program to Find LCM?
"""

# Function to find GCD of two numbers
def gcd(a, b):
    if b == 0:
        return a
    else:
        return gcd(b, a % b)

# Function to find LCM of two numbers
def lcm(a, b):
    return (a * b) // gcd(a, b)

# Get the two numbers from the user
num1 = int(input("Enter first number: "))
num2 = int(input("Enter second number: "))

# Find the LCM of the two numbers
lcm_num = lcm(num1, num2)

# Print the LCM
print("The LCM of", num1, "and", num2, "is", lcm_num)

"""### 2. Write a Python Program to Find HCF?"""

# Function to find HCF of two numbers
def hcf(a, b):
    if b == 0:
        return a
    else:
        return hcf(b, a % b)

# Get the two numbers from the user
num1 = int(input("Enter first number: "))
num2 = int(input("Enter second number: "))

# Find the HCF of the two numbers
hcf_num = hcf(num1, num2)

# Print the HCF
print("The HCF of", num1, "and", num2, "is", hcf_num)

"""### 3. Write a Python Program to Convert Decimal to Binary, Octal and Hexadecimal?"""

# Get the decimal number from the user
decimal_num = int(input("Enter a decimal number: "))

# Convert to binary, octal and hexadecimal
binary_num = bin(decimal_num)
octal_num = oct(decimal_num)
hexadecimal_num = hex(decimal_num)

# Print the results
print("The decimal number", decimal_num, "is equivalent to:")
print("Binary number:", binary_num)
print("Octal number:", octal_num)
print("Hexadecimal number:", hexadecimal_num)

"""### 4. Write a Python Program To Find ASCII value of a character?"""

# Get the character from the user
char = input("Enter a character: ")

# Convert the character to its ASCII value
ascii_value = ord(char)

# Print the ASCII value
print("The ASCII value of", char, "is", ascii_value)

"""### 5. Write a Python Program to Make a Simple Calculator with 4 basic mathematical operations?"""

# Define the function to perform the calculation
def calculator(num1, operator, num2):
    if operator == '+':
        return num1 + num2
    elif operator == '-':
        return num1 - num2
    elif operator == '*':
        return num1 * num2
    elif operator == '/':
        if num2 == 0:
            return "Cannot divide by zero"
        else:
            return num1 / num2
    else:
        return "Invalid operator"

# Get input from the user
num1 = float(input("Enter the first number: "))
operator = input("Enter the operator (+, -, *, /): ")
num2 = float(input("Enter the second number: "))

# Perform the calculation
result = calculator(num1, operator, num2)

# Print the result
print(num1, operator, num2, "=", result)

